# Generated by Django 5.1.3 on 2024-11-22 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_homepage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostpage",
            name="subject_film",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="website.film",
            ),
        ),
        migrations.DeleteModel(
            name="MovieReviewPost",
        ),
    ]
