# Generated by Django 5.1.3 on 2024-11-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_blogpostpage_subject_film_delete_moviereviewpost"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="showtime",
            name="unique_showtime_per_theater",
        ),
        migrations.RemoveField(
            model_name="showtime",
            name="theater",
        ),
    ]
