# Generated by Django 5.1.3 on 2024-11-28 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("website", "0008_remove_showtime_unique_showtime_per_theater_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogauthor",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
