# Generated by Django 5.1.3 on 2024-12-07 14:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("website", "0010_alter_homepage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="banner_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 12),
                    ("coming_soon", 13),
                    ("now_playing", 15),
                    ("recent_posts", 13),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Call-to-action text",
                            "required": False,
                            "verbose_name": "Call-to-action text",
                        },
                    ),
                    4: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Link to a page",
                            "required": False,
                            "verbose_name": "Call-to-action Page link",
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("Read More", "Read More"),
                                ("Learn More", "Learn More"),
                            ],
                            "help_text": "Choose link text",
                            "required": False,
                            "verbose_name": "Call-to-action Link text",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("cta_text", 3), ("cta_page_link", 4), ("cta_link_text", 5)]],
                        {"required": False},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "", "required": False},
                    ),
                    8: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the ID attribute you would like to link",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("page_link", 8), ("anchor_link", 9)]],
                        {"label": "Primary Button", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("page_link", 8), ("anchor_link", 9)]],
                        {"label": "Secondary Button", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header_text", 0),
                                ("sub_header_text", 1),
                                ("background_image", 2),
                                ("cta", 6),
                                ("primary_button", 10),
                                ("secondary_button", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.StructBlock", [[]], {}),
                    14: ("wagtail.blocks.CharBlock", (), {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 14), ("block_text", 14)]],
                        {},
                    ),
                },
            ),
        ),
    ]
