# Generated by Django 5.1.3 on 2024-12-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_film_banner_image_alter_homepage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="omdb_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
