# Generated by Django 5.1.3 on 2024-12-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_film_omdb_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
