# Generated by Django 5.1.3 on 2024-12-09 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_productionstill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="slug",
        ),
    ]
