# Generated by Django 5.1.3 on 2024-12-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0015_remove_film_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpostpage",
            name="subject_film",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="productionstill",
            name="film",
        ),
        migrations.RemoveField(
            model_name="productionstill",
            name="still_image",
        ),
        migrations.RemoveField(
            model_name="showtime",
            name="schedule",
        ),
        migrations.DeleteModel(
            name="Film",
        ),
        migrations.DeleteModel(
            name="ProductionStill",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
        migrations.DeleteModel(
            name="ShowTime",
        ),
    ]
