# Generated by Django 5.1.3 on 2024-12-10 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_productionstill"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductionStill",
        ),
    ]
