# Generated by Django 5.1.3 on 2024-12-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0022_blogpostpage_subject_film"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Theater",
        ),
    ]
