# Generated by Django 5.1.3 on 2024-11-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="showtime",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
