# Generated by Django 5.1.3 on 2024-11-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0002_schedule_confirmed_showtime_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="imdb_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="film",
            name="youtube_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
